import courseJson from '@/content/course.json';
import dependenciesJson from '@/content/dependencies.json';
import errataJson from '@/content/errata.json';
import figuresJson from '@/content/figures.json';
import formulasJson from '@/content/formulas.json';
import glossaryJson from '@/content/glossary.json';
import questionsJson from '@/content/questions.json';
import searchIndexJson from '@/content/search-index.json';
import sourcesJson from '@/content/sources.json';
import lecture01 from '@/content/lectures/01.json';
import lecture02 from '@/content/lectures/02.json';
import lecture03 from '@/content/lectures/03.json';
import lecture04 from '@/content/lectures/04.json';
import lecture05 from '@/content/lectures/05.json';
import lecture06 from '@/content/lectures/06.json';
import lecture07 from '@/content/lectures/07.json';
import lecture08 from '@/content/lectures/08.json';
import lecture09 from '@/content/lectures/09.json';
import lecture10 from '@/content/lectures/10.json';
import lecture11 from '@/content/lectures/11.json';
import lecture12 from '@/content/lectures/12.json';
import lecture13 from '@/content/lectures/13.json';
import lecture14 from '@/content/lectures/14.json';
import lecture15 from '@/content/lectures/15.json';
import lecture16 from '@/content/lectures/16.json';
import lecture17 from '@/content/lectures/17.json';
import lecture18 from '@/content/lectures/18.json';
import lecture19 from '@/content/lectures/19.json';
import lecture20 from '@/content/lectures/20.json';
import lecture21 from '@/content/lectures/21.json';
import lecture22 from '@/content/lectures/22.json';
import lecture23 from '@/content/lectures/23.json';
import lecture24 from '@/content/lectures/24.json';
import lecture25 from '@/content/lectures/25.json';
import lecture26 from '@/content/lectures/26.json';
import lecture27 from '@/content/lectures/27.json';
import type { CourseSummary, Formula, GlossaryEntry, Lecture, Question, SearchRecord, SourceIndexEntry } from './types';

export const course = courseJson as unknown as CourseSummary[];
export const lectures = [lecture01, lecture02, lecture03, lecture04, lecture05, lecture06, lecture07, lecture08, lecture09, lecture10, lecture11, lecture12, lecture13, lecture14, lecture15, lecture16, lecture17, lecture18, lecture19, lecture20, lecture21, lecture22, lecture23, lecture24, lecture25, lecture26, lecture27] as unknown as Lecture[];
export const lectureBySlug = new Map(lectures.map((lecture) => [lecture.slug, lecture]));
export const questions = questionsJson as unknown as Question[];
export const glossary = glossaryJson as unknown as GlossaryEntry[];
export const formulas = formulasJson as unknown as Formula[];
export const searchIndex = searchIndexJson as unknown as SearchRecord[];
export const sources = sourcesJson as unknown as SourceIndexEntry[];
export const errata = errataJson;
export const figures = figuresJson;
export const dependencies = dependenciesJson as { from: number; to: number }[];
